### ISSUE TITLE
Zabbix JMXOBJ in reverse order

### ISSUE THREAD

**Issue by bporter2387** [RiotGamesMinions/zabbix_jmxdiscovery#3]
While you can compose the correct item prototype using #PROPNAME and PROPTYPE, it would be nice to use #JMXOBJ by itself. The issue is that the #JMXOBJ string should have 'name' and 'type' reversed. 

The Jconsole object name is "kafka.network":type="RequestMetrics",name="Fetch-RequestsPerSec"

It should return ('type' first)
"{#JMXOBJ}": "\"kafka.network\":type=\"RequestMetrics\",name=\"Fetch-RequestsPerSec\""

But it returns:
"{#JMXOBJ}": "\"kafka.network\":name=\"Fetch-RequestsPerSec\",type=\"RequestMetrics\""

I'm not really a Java guy, but I went into the code and saw it's calling 

bean.put("{#JMXOBJ}", beanName.getCanonicalName()); // Line 89

Maybe there's another method that can be called to get the correct object name?

**Comment by bporter2387** [comment]
Changing line 89 from 

bean.put("{#JMXOBJ}", beanName.getCanonicalName());

to 

bean.put("{#JMXOBJ}", beanName.toString());

seemed to do the trick.

**Comment by bunjiboys** [comment]
If you wouldn't mind making a pull-request and I'll take a look at it. I don't see any big problems doing this however.

**Comment by bunjiboys** [comment]
Fixed by https://github.com/RiotGamesMinions/zabbix_jmxdiscovery/pull/4
